//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio.Recursos {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Textos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Textos() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dominio.Recursos.Textos", typeof(Textos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La operación fue cancelada con éxito.
        /// </summary>
        public static string CanceladoExitoso_Generico {
            get {
                return ResourceManager.GetString("CanceladoExitoso_Generico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string Cancelar {
            get {
                return ResourceManager.GetString("Cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmación.
        /// </summary>
        public static string Confirmacion {
            get {
                return ResourceManager.GetString("Confirmacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Está seguro que desea eliminar este elemento?.
        /// </summary>
        public static string ConfirmacionBorrado {
            get {
                return ResourceManager.GetString("ConfirmacionBorrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ejecutar.
        /// </summary>
        public static string Ejecutar {
            get {
                return ResourceManager.GetString("Ejecutar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar.
        /// </summary>
        public static string Eliminar {
            get {
                return ResourceManager.GetString("Eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error al actualizar los datos.
        /// </summary>
        public static string Error_ActualizarGenerico {
            get {
                return ResourceManager.GetString("Error_ActualizarGenerico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El objeto esta siendo utilizado por otras entidades.
        /// </summary>
        public static string Error_EliminarReferenciado {
            get {
                return ResourceManager.GetString("Error_EliminarReferenciado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error. Por favor intente nuevamente más tarde..
        /// </summary>
        public static string Error_Generico {
            get {
                return ResourceManager.GetString("Error_Generico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La operación fue exitosa.
        /// </summary>
        public static string Exito_Generico {
            get {
                return ResourceManager.GetString("Exito_Generico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        public static string Guardar {
            get {
                return ResourceManager.GetString("Guardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensaje.
        /// </summary>
        public static string Menu_Mensaje {
            get {
                return ResourceManager.GetString("Menu_Mensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titulo.
        /// </summary>
        public static string Menu_Titulo {
            get {
                return ResourceManager.GetString("Menu_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar.
        /// </summary>
        public static string Modificar {
            get {
                return ResourceManager.GetString("Modificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar.
        /// </summary>
        public static string Seleccionar {
            get {
                return ResourceManager.GetString("Seleccionar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si.
        /// </summary>
        public static string Si {
            get {
                return ResourceManager.GetString("Si", resourceCulture);
            }
        }
    }
}
